- src/client/App.tsx
- src/client/views/AiConversations.tsx
- src/client/views/Chatroom.tsx
- src/client/views/CreateEvents.tsx
- src/client/views/Events.tsx
- src/client/views/Signup.tsx
- src/client/views/Task.tsx
- src/client/views/index.tsx
- src/server/app.ts
- src/server/routes/ai.ts
- src/server/routes/aiConversation.ts
- src/server/routes/aiTask.ts
- src/server/routes/avatar.ts
- src/server/routes/index.ts
Updated folder structure for your enjoyment
> Add routes

- package-lock.json
- package.json
- src/server/app.ts
- src/server/db/index.ts
- tsconfig.json
- Added dependencies for starting server with typescript:
- @types/express
- @types/node
- concurrently
- ts-node
- Updates to tsconfig.json:
- noEmit: true
- skipLibCheck: true
- Add type-checking to the passport process and database authentication
> Typescript Updates

- src/server/app.ts
- src/server/index.ts
- src/server/routes/ai.ts
- src/server/routes/aiConversation.ts
- src/server/routes/aiTask.ts
- src/server/routes/auth.ts
- src/server/routes/avatar.ts
- src/server/routes/chat.ts
- src/server/routes/chatroom.ts
- src/server/routes/event.ts
- src/server/routes/event2.ts
- src/server/routes/flare.ts
- src/server/routes/index.ts
- src/server/routes/signup.ts
- src/server/routes/task.ts
- src/server/routes/user.ts
Fix syntax errors for routes
Fix most errors in server/app.ts and server/index.ts
- Some errors could not be fixed, need to check eslint config
> Syntax Errors

- .eslintrc.js
- src/server/db/models/tasks.ts
- src/server/db/models/users_tasks.ts
Update eslintrc file with new rules
> Lint Update

- src/client/views/Events.tsx
- src/server/db/seeds/seedEvents.ts
- Grab the user's location when visiting the Events view and store in the state
- Start building a seed function to store events in the database for development
> feat: Events Location & build: Seed Data

- src/client/App.tsx
- src/client/views/Dashboard.tsx
- src/client/views/Events.tsx
- src/client/views/Home.tsx
- src/client/views/index.tsx
- src/server/app.ts
- src/server/db/models/index.ts
- src/server/db/models/users.ts
- src/server/db/seeds/seedEvents.ts
- req.user now contains the user object from SQL database
- Added Dashboard view to act as the landing page for login/sign up
- Update seedEvents function to seed three events on use
> feat / Update Auth

- src/client/views/Signup.tsx
- src/server/db/seeds/seedInterests.ts
- src/server/routes/signup.ts
-ADJUST routes for signup to account for google strategy
- ADJUST frontend to redirect to the dashboard based on conditional
> Debug signup

- src/client/components/events-view/Event.tsx
- src/client/components/events-view/EventsList.tsx
- src/client/views/Events.tsx
- src/server/api.ts
- src/server/app.ts
- src/server/db/models/users_events.ts
- src/server/routes/event2.ts
- BIG UPDATE: endpoints to our routers begin with "/api" now
- User can attend and event now
> feat / Use can attend events

- package-lock.json
- package.json
- src/server/db/models/conversations.ts
- src/server/db/models/index.ts
- src/server/routes/aiConversation.ts
1. Import the google generative ai client, load env
2. Create a gemini client
3. On POST "/":
a) read "prompt" + "userId" from the request
b) call the gemini API with advanced prompt
c) store the conversation in DB
d) return the new conversation
> Feat aiconversation

- src/components/ui/button.tsx
- src/components/ui/card.tsx
- src/components/ui/input.tsx
- src/components/ui/interactive-hover-button.tsx
- src/components/ui/label.tsx
- src/components/ui/magicCard.tsx
- src/components/ui/rainbowbutton.tsx
- src/components/ui/select.tsx
- src/components/ui/shiny-button.tsx
- src/components/ui/sparkletext.tsx
- src/components/ui/tabs.tsx
- webpack.config.js
eslint refactor for components ui
> Debug destructuring

- package-lock.json
- package.json
> fix / Pixi

- src/client/App.tsx
- src/client/contexts/UserContext.ts
- src/client/views/Events.tsx
- src/client/views/Home.tsx
- src/server/routes/user.ts
- At the top level of your view:
- import { useContext } from 'react'
- import { UserContext } from '../contexts/UserContext'
- At the top of your component function:
- const { user, setUser } = useContext(UserContext);
- user => user object from DB
- setUser => sets the state of user
> feat / User Context for App

- package-lock.json
- package.json
- src/client/components/events-view/Event.tsx
- src/client/components/events-view/EventDetails.tsx
- src/client/views/Events.tsx
- src/components/ui/drawer.tsx
- src/server/routes/event2.ts
- src/server/routes/user.ts
npm install => New dependency for "drawer" component
- Hide details in a drawer that opens on button press
- Chatroom button appears if you are attending an event
> feat / Events polish

- package-lock.json
- package.json
- src/client/App.tsx
- src/client/components/chatroom/MsgBox.tsx
- src/client/views/Chatroom.tsx
- src/components/ui/animated-list.tsx
- src/server/index.ts
- src/server/routes/chatroom.ts
- webpack.config.js
FEAT Users can now see chat messages in the game!
FEAT Users can now see their chat messages animated in the game!
> Feat chatrouter

- package.json
- src/server/db/seeds/seedEvents.ts
- Add seed scripts
- Update seedEvents
- seedTasks NEEDS work
> Seeds Update

- src/server/db/models/events.ts
- src/server/routes/event2.ts
Fixed events
- May need to drop database but test first.
> Fix events

- src/client/components/tasks/ChooseTask.tsx
- src/client/components/tasks/DifficultyButton.tsx
- src/client/components/tasks/TaskDisplay.tsx
- src/client/components/tasks/TypeButton.tsx
- src/client/views/Dashboard.tsx
- src/server/db/models/events_categories.ts
- src/server/db/models/tasks.ts
- src/server/db/seeds/seedTasks.ts
- src/server/routes/task.ts
Change the foreign key declaration on event_categories model
The server now starts
> Event categories

- src/client/components/chatroom/MsgBox.tsx
- src/client/components/signup/avatar.tsx
- src/client/components/signup/avatarSelection.tsx
- src/client/views/Chatroom.tsx
- src/client/views/Dashboard.tsx
- src/client/views/Signup.tsx
- src/server/index.ts
- BUG require socket rooms to ensure players join unique chatrooms
- BUG unable to send user to socket on emit
- REFACTOR removed console log statements 
- MOVE avatar selection to dashboard to prevent faulty submission of signup form
- FEAT selected avatar lights up green when clicked for user
> Feat chatupgrade

- src/client/components/events-view/EventDetails.tsx
- src/client/components/events-view/EventsList.tsx
- src/client/views/Events.tsx
- src/server/db/seeds/seedEvents.ts
- src/server/routes/event2.ts
- User can see events in any city/state, defaults to current location
- Filtering happens on the server interacting with the database.
> Filter Events By Location

- src/server/db/models/events.ts
- src/server/db/models/events_interests.ts
- src/server/db/models/notifications.ts
- src/server/db/models/users_notifications.ts
- src/server/routes/user.ts
- Update GET /api/user to include Interests & Notifications
- Update Events table with hour_before_notif field
> feat / Notifications Prep

- src/client/assets/chatroom/chatAssets.tsx
- src/client/components/NavBar.tsx
- src/server/index.ts
- src/server/socket.ts
- src/types/Players.tsx
-Removed chatroom and signup from the nav bar
-Add logout button that logs user out
-BUG can still access other pages while user is signed out. Will cause server errors
-LOW COUPLING . HIGH COHESION . POLYMORPHISM
moved sockets out of database into socket.ts 
moved types & player constructor functions from database into assets
-DEBUG User is now sent to signup page if user is authorized via google but DOES NOT have an account.
-
-
> DEBUG_Authorization

- src/client/components/events-view/Event.tsx
- src/client/components/events-view/EventsList.tsx
- src/client/views/Events.tsx
- src/server/routes/event2.ts
- Notifications are created for user when they attend/bail from an event
> feat / Event Notifications

- src/client/App.tsx
- src/client/components/NavBar.tsx
- src/client/contexts/UserContext.ts
- src/client/views/Notifications.tsx
- src/client/views/index.tsx
- src/server/routes/user.ts
- Notifications react to user attending and bailing from an event
- Updated GET /api/user handler to send notifications after send_time
- Created Notifications view to work on displaying notifications
- Updated UserContext and UserType to have interests and notifications
- User can see their notifications
- Will work on cleaning up this view tomorrow
> feat / User can see filtered Notifications

- src/client/components/tasks/OptOutTask.tsx
- src/client/components/tasks/TaskDisplay.tsx
- src/server/db/models/users_tasks.ts
- src/server/routes/task.ts
> Opt out list items have a retry button 
> Retry button changes current task to the previously opted out of task
> On the back end the corresponding user_task opted_out column is toggled to false
**Still need restyling on the task view**
> Opt Back in to Task

- src/client/components/tasks/ChooseTask.tsx
- src/client/components/tasks/DialogBox.tsx
- src/client/components/tasks/OptOutTask.tsx
- src/client/components/tasks/TaskDisplay.tsx
> Confirm a user wants to perform an action with dialog boxes
> Users must confirm when they are choosing a task, opting out of a task, or retrying a task
> Dialog box allows them to cancel or confirm the action  
> Kept dialog box code separate to keep code neater
> Component can be reused when passed the necessary props
**Need to style DialogBox component**
> Task Fail-Safes

- src/client/App.tsx
- src/client/components/NavBar.tsx
- src/client/views/Events.tsx
- src/client/views/Notifications.tsx
- src/server/api.ts
- src/server/routes/index.ts
- src/server/routes/notifications.ts
- src/server/routes/user.ts
- Add notifications router on backend
- Add notifications to NavBar and front end route
- Clean up logs in Events view
- Add GET /api/notifications handler
- Optional query can be used to filter notifications based on `seen` field
- Notifications currently display as cards, subject to change
> Notifications work

- src/client/components/NavBar.tsx
- src/client/components/notifications-view/Notification.tsx
- src/client/components/notifications-view/NotificationList.tsx
- src/client/views/Notifications.tsx
- src/server/routes/notifications.ts
- src/server/routes/user.ts
- Added the following server handlers
- PATCH /api/notifications/seen/all
- DELETE /api/notifications/:id
- DELETE /api/notifications/all
- Refactor Notifications view to have custom components, NotificationList & Notification
- Add number of unread notifs to NavBar
- Sort notifications by seen, then send_time
- Adjust GET /api/user to only send back unread notifications
> feat / Notifications Display

- package-lock.json
- package.json
- src/client/components/events-view/EventDetails.tsx
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/components/ui/dialog.tsx
- src/components/ui/radio-group.tsx
- src/server/api.ts
- src/server/db/models/texts.ts
- src/server/routes/event2.ts
- src/server/routes/index.ts
- src/server/routes/text.ts
- Add /api/text router for request handling for texts
- Adjusted Text model
- User can schedule a text to be sent during an event
- User can see the info associated with the scheduled text
> feat / Text Feature: C & R set up

- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/views/Notifications.tsx
- src/server/index.ts
- src/server/routes/event2.ts
- src/server/routes/text.ts
- src/server/workers/texts.ts
- Added the following request handlers:
- PATCH /api/text/:eventId
- DELETE /api/text/:eventId
- User can update a previously scheduled text
- User can delete a previously scheduled text
- When a user bails, the scheduled text gets deleted
- Set up worker file to send scheduled texts and import into server entry point
> feat / Text Feat Finish - Full CRUD

- src/client/components/chatroom/QuipLash.tsx
- src/client/views/Chatroom.tsx
- src/server/socket.ts
- webpack.config.js
> DEBUG switch socket initialization to use https slayer events

- src/server/app.ts
> final attempt

- src/client/components/chatroom/QuipLash.tsx
- src/client/views/Chatroom.tsx
- src/server/socket.ts
- webpack.config.js
> REFACTOR switched back to the way i tried on pr 105

- src/client/components/events-view/Event.tsx
- src/client/components/events-view/EventDetails.tsx
- src/client/components/events-view/LocationFilter.tsx
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/views/Events.tsx
- src/client/views/Notifications.tsx
- Updated the styling of the Events view to match the general theme closer.
- Notifications got the background but needs more work
> style / Events View

- src/client/components/tasks/ChooseTask.tsx
- src/client/components/tasks/OptOutTask.tsx
- src/client/components/tasks/TaskDisplay.tsx
- src/client/views/Dashboard.tsx
- src/client/views/Task.tsx
> Create breakpoints for components in the task view to control width
> Changed the background to match the rest of the application
> Change the background and text color of these card components
> Change the min height of these components
> Hovering over an opted out task highlights gray with 50% opacity to try and let a user know the row is clickable
> Task styles

- src/client/components/chatroom/QuipLash.tsx
- src/client/views/Chatroom.tsx
- src/server/socket.ts
Minor styling update, still in progress.
> Game styles

- tests/events.test.ts
- tests/teardown.ts
- tests/texts.test.ts
- Added tests for the following server handlers
- POST /api/text
- GET /api/text/:eventId
- PATCH /api/text/:eventId
- DELETE /api/text/:eventId
> test / Texts Handlers Test Suite

- src/client/components/tasks/AchievementCard.tsx
- src/client/components/tasks/taskSidebar.tsx
- src/client/views/Task.tsx
- src/server/db/models/flares.ts
- src/server/db/seeds/seedFlares.ts
- src/server/routes/flare.ts
> Create a TaskSidebar component for the Task view
> Sidebar contains the last week task count and current week task count
> Sidebar shows user the Task flares they've earned
> Task sidebar

- src/server/routes/event2.ts
- tests/notifications.test.ts
- tests/setup.ts
- tests/teardown.ts
- tsconfig.json
- Add Notifications Test Suite:
- POST /api/event/attend/:id
- GET /api/notifications
- Bug?: If I add anything else to notifications.test.ts, the `jest` stops working for the file.
- Refactor: POST /api/event/attend/:id no longer needs a body to complete request.
> test / Test Notifications Suite

- src/client/components/a11y/TTSButton.tsx
- src/client/components/notifications-view/Notification.tsx
- Created TTSButton component to be used throughout app
- text: The message to be read on button click
- className: The buttons className for tailwindcss styling
- iconClassName: The Icon's className for tailwindcss styling
- The button debounces multiple requests for users that may multi-request the TTS
> a11y / TTS Button

- src/server/db/seeds/seedFlares.ts
- src/server/helpers/flares.ts
> New Flare 'Venue Virtuoso' for updating venue information
> Had to push for Colton
> Add Flare For Colton

- package.json
- src/server/db/seeds/index.ts
> build / Database sync

- package.json
- src/server/db/seeds/index.ts
- src/server/db/seeds/seedTasks.ts
- tests/server/setup.ts
- Removed seedTasks from the general seed for GitHub runner
> build / Remove seed tasks

- src/client/views/CreateEvents.tsx
- src/server/routes/event.ts
- Fixes bug where venue_id isn't added to events upon form submission
- commented out lat and long in fsq api query
> FIX venueid bug 

- .github/workflows/node.js.yml
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/components/general/HeadlessDialog.tsx
- src/client/views/Events.tsx
- src/client/views/Notifications.tsx
- Add toasts for texts feature
- Created a general dialog component to be reused
- Location: src/client/components/general/HeadlessDialog.tsx
- Includes TTSButton to read title and description
- Add dialog when deleting all notifications
- Disabled delete all notifications button if no notifications are available
- CI Update: Only testing node 20 now
> feat / Notifications & Texts Polish

- package-lock.json
- package.json
- src/client/assets/chatroom/chatAssets.tsx
- src/client/components/chatroom/MsgBox.tsx
- src/client/components/chatroom/QuipLash.tsx
- src/client/components/chatroom/countdown.tsx
- src/client/views/Chatroom.tsx
- src/components/ui/scroll-based-velocity.tsx
- src/server/routes/chatroom.ts
you must "npm run update"
-DEBUG buttons:
no longer allows u to quit without closing game
only opens game when allowed
user cannot trigger timer faults
DEBUG:
timestamps now appear on messages
user can now send longer messages and see them
UPDATEL game now loads Quiplash prompts on screen
FEAT
winning a game of quiplash is more satisfying
> Debug chat 7

- src/client/components/event-form/VenueSearch.tsx
- src/server/routes/event.ts
- API call was getting executed before geoLocation value was returned
- If you don't see venue results populate from the api, wait a second, clear the search input and try again
- That geoLocation just takes a second >.< Will need to figure out a better fix in the future.
> FIX form bugs

- src/server/routes/event.ts
- Not sure if this just never existed or what, but event route is creating the user notif column now as well as the Notification
> ADD User_Notification

- src/client/components/signup/AvatarStep.tsx
- src/client/components/signup/InterestsStep.tsx
- src/client/components/signup/UserInfoStep.tsx
- src/client/views/Signup.tsx
- src/components/ui/alert.tsx
- src/server/db/seeds/index.ts
Refactored Signup.tsx into multiple components
- signup/AvatarStep.tsx
- signup/InterestsStep.tsx
- signup/UserInfoStep.tsx
- views/Signup.tsx PARENT
Added error handling so that...
- User must input username and phone number fields
- User can only enter numbers into phone number field
- User is notified if their number exceeds 10 digits
- User is notified if their username exceeds 15 chars
> Small Updates

- src/client/components/chatroom/QuipLash.tsx
- src/client/views/Chatroom.tsx
- src/server/routes/chatroom.ts
Minor bug fixing:
DEBUGS:
If there is no winner, no longer shows all '0'
Ready Button disappears appropriately
> Feat avatars

- package-lock.json
- src/client/components/events-view/LocationFilter.tsx
- src/client/views/Events.tsx
- Had to reinstall deps and it changed the package-lock.json
- Everything still works as far as I can see, but wanted to keep everyone in the loop
- Refactored event view to use a component for the location filter to help with the organization of the view
> refactor / Separate Location Filter Into Component

- src/client/components/events-view/CategoryFilter.tsx
- src/client/components/events-view/LocationFilter.tsx
- src/client/views/Events.tsx
- src/server/routes/event2.ts
- Sidebar for event filters
- User can sort events by category
> feat / Sort Events By Category

- src/client/components/events-view/InterestsFilter.tsx
- src/client/views/Events.tsx
- src/server/routes/event2.ts
- User will see events based on their selected interests
- User can adjust these interests in the events view to see other events if desired
> feat / Events Filter By Interests

- src/client/assets/chatroom/chatAssets.tsx
- src/client/views/Chatroom.tsx
- src/server/routes/chatroom.ts
- src/server/socket.ts
FEAT : User avatars now load into the game for each respective player
> Feat in game avatars

- src/client/components/events-view/Event.tsx
- src/client/components/events-view/VenueDetails.tsx
- Shortened URL appears underneath the website button
- Fixed height and image size for Event cards
- Centered card content
- Using icons for:
- Host: "H"
- Attending: "A"
- Bailed: "B"
> style / Cleaned Up Event Cards

- src/client/App.tsx
- src/client/components/NavBar.tsx
- src/client/views/Dashboard.tsx
- src/client/views/Home.tsx
- src/components/ui/landing-nav.tsx
- Keep just one button on dash change to say Sign up or Login w/ Google
- Improve button contrast and readability
- Add consistent Google icon styling
- Update button text for clarity
- - Add GitHub link to team name in dashboard footer
- Maintain consistent styling with landing page
- Improve footer accessibility
> Feat/link GitHub

- src/client/components/events-view/Event.tsx
- src/client/components/events-view/EventDetails.tsx
- src/client/components/events-view/EventDrawerContent.tsx
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/components/notifications-view/Notification.tsx
- Increase Icon Size on Event cards
- Center title and description for Event Details
- Adjust button colors to match general theme better (no more green)
- "x" text changed to "x" icon
- Update text dialog background to match general theme better
> style / Style Adjustments for Events, Texts, & Notifs

- src/client/components/events-view/EventDetails.tsx
- src/client/components/events-view/EventDrawerContent.tsx
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/components/events-view/VenueDetails.tsx
- Mirror button colors for side by side buttons of similar color
- Align title and icons for details components
- Tooltip the full website URL a user will visit on button click
- Adjust size of button for visiting website
> style / Events style update

- src/client/components/events-view/Event.tsx
- src/client/components/events-view/EventDetails.tsx
- src/client/components/events-view/EventDrawerContent.tsx
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/components/events-view/VenueDetails.tsx
- Event details on text modal
- Adjust close button color
- Styled scroll bar for event details drawer
- Remove question marks from venue details
- Centered arrows below venue pics
> style / Events view update

- src/client/views/Chatroom.tsx
animation was wonky on full-screen. fixed it
> Animation debug

- src/client/App.tsx
- src/client/components/NavBar.tsx
- src/client/views/Dashboard.tsx
- src/client/views/Home.tsx
- src/components/ui/landing-nav.tsx
This reverts commit f782744c8e443cb485096e6f0ff70998d224f4e8, reversing changes made to 3b15b9102ae1394e13ab2f5a04911ee0b61f72fc.
- reverting to the previous pr because there are too many merge conflicts with the latest
> Revert "Merge pull request #183 from atheriot827/feat/link-github"

- package.json
- src/server/db/showcase-seeds/index.ts
- src/server/db/showcase-seeds/seedFlares.ts
- src/server/db/showcase-seeds/seedTasks.ts
- Started the Showcase Seed function
- I may have to modify the seed tasks and and seed flare functions
- I made a copy of them in a showcase-seeds directory to not interfere with the seeds we're using in development and production
> seed / Showcase seed

- src/client/components/chatroom/DJam.tsx
- src/client/components/chatroom/MacroRecorder.tsx
- src/client/views/Chatroom.tsx
- src/server/db/models/chats.ts
- src/server/routes/chatroom.ts
Patch Includes
DJam Game:
-User can store macros in database.
-Users can publish macros
-Users can get other players macros
-Users can remix other player macros
-A Screen That displays buttons for each published macro that allow user to play them when clicked, as well as edit them to create their own version.
Chatroom:
-Update UI For Large Screen Chatroom
-Set Game to smaller screen and off to the left
-Have chat displayed on right side of chatroom along with input. This feature should remain consistent across all games. on large screens ONLY
PLANS:
-More sleek appearance for Game UI
-Load Avatar into Message Box
-Add 2 Accessory Items for Character to Wear. (Tuesday)
-Add backing music for Chatroom
-Add Sound Effects to Flamiliar
-Add backing music for Chatroom
-Add Sound Effects to …
> Chat patch 2

- src/client/components/general/ReadMore.tsx
- src/client/components/notifications-view/Notification.tsx
- src/client/components/notifications-view/NotificationList.tsx
- src/client/views/Notifications.tsx
- Add the title to the Notification type
- Update the TTS button to include the title when reading notifications
- Include the title on the Notification cards
- Add conditional to render a default title "Notification" if a title isn't provided
- Create a general ReadMore component to collapse long messages with `Read More` and `Read Less` buttons
- To use:
- Wrap the text you want to collapse in the ReadMore component and set a max length to detect if the text needs to be collapsed
- `children` refers to the text being wrapped by the ReadMore component
- `maxLength` refers to the maximum number of characters the text can be before it is collapsed by the ReadMore component
- `className` is used to style the text inside the ReadMore component
- ReadMore is essentially a `<div>` containing …
> feat / Notification itle

- src/client/components/tasks/CompletedTask.tsx
- src/client/components/tasks/CompletedTaskList.tsx
- src/client/views/Task.tsx
- src/server/routes/userTask.ts
> Users can filter completed tasks by task type 
> Dropdown is how user chooses filter
> May need some slight styling on the dropdown
> Task Filter

- .gitignore
- package-lock.json
- src/client/components/event-form/ImageSelection.tsx
- src/client/components/event-form/ItemSelection.tsx
- src/client/components/event-form/Review.tsx
- src/client/views/CreateEvents.tsx
- src/server/api.ts
- src/server/db/models/event_venue_tags.ts
- src/server/db/models/events.ts
- src/server/db/models/index.ts
- src/server/db/models/venue_tags.ts
- src/server/routes/event.ts
- src/server/routes/index.ts
- src/server/routes/venueRoute.ts
- webpack.config.js
[EDIT] - Build failed due to a missing crypto module that Axios was requesting. Error suggested to add the crypto module to webpacks resolve.fallback to ignore it. Hope this works. As far as my knowledge extends, we are not using the crypto module anywhere unless it snuck into our codebase somehow. 
[EDIT 2] - Sick it worked
- Adds new join table for user selected hashtags 
- Refactored interest & hashtag selection to reusable component
- Fixed display_order so records being saved have proper display_order in DB
- Created new route for venue related queries, may remove.. Just feeling like my event router is getting insane. Planning to optimize soon so will see if this new route stays or not. 🧯.
> UPDATE models & form

- src/client/views/CreateEvents.tsx
- src/server/routes/event.ts
Ignore 99% of these line changes - switched to my laptop and I guess my formatter or something is going crazy, only had to change 2~ lines.
> FIX missing venue id on event record

- src/client/views/Events.tsx
- src/server/routes/event2.ts
Short PR:
- The events appear in the order of soonest to latest in terms of start time
Looking into limiting the number of events to be returned using a query parameter.
> feat / Order Events On View By Date

- src/client/components/events-view/CategoryFilter.tsx
- src/client/components/events-view/FilterButtonsDialog.tsx
- src/client/components/events-view/InterestsFilter.tsx
- src/client/views/Events.tsx
- Interest and Category filter for events matches other forms by using a dialog on click
> feat / Polish Events Category and Interests Filters

- src/client/components/NavBar.tsx
- src/client/components/events-view/CategoryFilter.tsx
- src/client/components/events-view/InterestsFilter.tsx
- src/client/components/events-view/LocationFilter.tsx
- src/client/components/events-view/ScheduleTextDialog.tsx
- src/client/components/events-view/VenueDetails.tsx
- src/client/views/Events.tsx
- src/server/app.ts
- Get user data in five second intervals to update notifications and avatar info on NavBar
- This will update the user info from context for any part of the app every five seconds
- Update Venue Details TTS
- Inform user that they don't have a phone number saved in the text dialog if they don't
- Redirect to account settings if they want to schedule a message
- Shorten and fix styling for filter buttons
- Location Filter is now a dialog
- Site cookie now lasts four hours instead of one hour to prevent a user from losing access during their session.
> feat / Clean Up For Showcase

- declarations.d.ts
- jest.config.js
- jest.setup.ts
- src/client/App.tsx
- src/client/components/chatroom/Backgroundmusic.tsx
- src/client/components/chatroom/DJam.tsx
- src/client/components/chatroom/Flamiliar.tsx
- src/client/components/chatroom/FlamiliarTutorial.tsx
- src/client/components/chatroom/MacroRecorder.tsx
- src/client/components/chatroom/MainChat.tsx
- src/client/components/chatroom/Menu.tsx
- src/client/components/chatroom/MsgBox.tsx
- src/client/components/chatroom/Piano.tsx
- src/client/components/chatroom/PlayerCharacter.tsx
- src/client/components/chatroom/countdown.tsx
- src/client/components/chatroom/decoyText.tsx
- src/client/contexts/ChatroomContext.tsx
- src/client/contexts/SocketContext.tsx
- src/client/views/Chatroom.tsx
- src/components/ui/animated-list.tsx
- src/server/routes/chatroom.ts
- src/server/socket.ts
- src/types/Chatroom.ts
- src/types/images.d.ts
- tests/components/Chatroom.test.tsx
- tests/server/ChatroomServer.test.ts
- tests/server/jest.config.js
- tsconfig.json
Major performance overhaul and debugging
-Now using useMemo on components that I don't need to re-render on every tick of the socket
-Isolated / Compartmentalized real-time player positions socket component into PlayerCharacter component
-Broke Chatroom component into 4 smaller components
-Made use of useContext on all noticeable prop-drilling
-Add types to obvious variables
-referencing socket with useMemo to prevent recreation of multiple sockets during re-render
-ensured all socket event listeners are off and removed when finished
-unloading all assets when the chatroom dismounts
-implemented lazy loading on new playercharacter component
-Provided way to quit all games when all mobile phone
-Memory heap usage in development mode only increases 10-12MB per player and during intensive …
> Game patch 7

- src/client/components/Logo.tsx
- src/client/components/NavBar.tsx
- Increase base logo sizes for better visibility
- Add more distinct size differences between breakpoints
- Adjust mobile, tablet, and desktop sizes
- Maintain proper navbar proportions
- Ensure clear size transitions between viewports
> fix: update logo visibility and positioning

- src/client/components/chatroom/Backgroundmusic.tsx
- src/client/components/chatroom/Flamiliar.tsx
- src/client/components/chatroom/MacroRecorder.tsx
- src/client/components/chatroom/Piano.tsx
> Game patch 8

- src/client/views/Dashboard.tsx
> Remove unused placeholder variables from dashboard view
> Fix user's flares from jumping order
> Dashboard Bug Fix

- src/client/components/NavBar.tsx
- src/server/db/showcase-seeds/seedFlares.ts
- src/server/routes/notifications.ts
- New GET /api/notifications/unread/count handler on the back-end
- Update a new state value for unread notifications for the bell
- Fixes glitches associated with the user object
- Update showcase seed function to include Flare dialog descriptions
> fix / Unread Notifications & Seed Flares

- src/client/views/Dashboard.tsx
- src/server/routes/flare.ts
> Change /api/flare/:id req handler to send user flares back in reverse order
> Order of Flares
